---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: CooperRS/ha-workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: "ha-addons"
      repository_edge: "ha-addons-edge"
      repository_beta: "ha-addons-beta"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
